Repository jungsae/Well-Com, pull requests merged in 2024-02, with the labels that each got.

#8 [ADD] Vuetify추가
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.vue
  front-end/src/assets/logo.svg
  front-end/src/components/HelloWorld.vue
  front-end/src/main.js
  front-end/src/plugins/vuetify.js
  front-end/src/plugins/webfontloader.js
  front-end/src/views/HomeView.vue
  front-end/src/views/home.vue
  front-end/vue.config.js
Labels: 리뷰 진행 중

#9 [HOTFIX] 급합니다.
  front-end/package-lock.json
  front-end/src/components/LoginComponent.vue
  front-end/src/components/ParentComponent.vue
  front-end/src/components/SignInComponent.vue
  front-end/src/components/SignUpComponent.vue
  front-end/src/router/index.js
  src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
  src/main/java/com/wellcom/global/config/SecurityConfig.java
  src/main/java/com/wellcom/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/wellcom/global/jwt/service/JwtService.java
  src/main/java/com/wellcom/global/login/handler/LoginSuccessHandler.java
Labels: 도움 요청

#11 [FIX] 재요청
  .settings/org.eclipse.buildship.core.prefs
  src/main/java/com/wellcom/domain/Desk/Desk.java
  src/main/java/com/wellcom/domain/Item/Item.java
  src/main/java/com/wellcom/domain/Item/ItemStatus.java
  src/main/java/com/wellcom/domain/Item/Status.java
  src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
  src/main/java/com/wellcom/domain/Member/Member.java
  src/main/java/com/wellcom/domain/Record/Record.java
  src/main/java/com/wellcom/domain/Reservation/Reservation.java
  src/main/java/com/wellcom/domain/Reservation/Status.java
  src/main/java/com/wellcom/domain/SharingRoom/Controller/SharingRoomController.java
  src/main/java/com/wellcom/domain/SharingRoom/Dto/SharingRoomCreateReqDto.java
  src/main/java/com/wellcom/domain/SharingRoom/Dto/SharingRoomCreateResDto.java
  src/main/java/com/wellcom/domain/SharingRoom/Repository/SharingRoomRepository.java
  src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
  src/main/java/com/wellcom/domain/SharingRoom/SharingRoom.java
  src/main/java/com/wellcom/domain/common/CommonResponse.java
  src/main/resources/application.yml
Labels: 리뷰 진행 중

#13 [ADD] Desk - Create/Read
  src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
  src/main/java/com/wellcom/domain/Desk/Desk.java
  src/main/java/com/wellcom/domain/Desk/Dto/DeskCreateReqDto.java
  src/main/java/com/wellcom/domain/Desk/Dto/DeskResDto.java
  src/main/java/com/wellcom/domain/Desk/Dto/testDto.java
  src/main/java/com/wellcom/domain/Desk/Repository/DeskRepository.java
  src/main/java/com/wellcom/domain/Desk/Service/DeskService.java
  src/main/java/com/wellcom/domain/Desk/Status.java
  src/main/java/com/wellcom/domain/common/ExceptionHandlerClass.java
  src/main/resources/application.yml
Labels: 완료

#17 [UPDATE] CRUD API 수정
  src/main/java/com/wellcom/domain/SharingRoom/Controller/SharingRoomController.java
Labels: 완료

#18 [FIX] 에약 로직에서 발생한 에러 및 버그 수정
  src/main/java/com/wellcom/domain/Reservation/Controller/ReservationController.java
  src/main/java/com/wellcom/domain/Reservation/Repository/ReservationRepository.java
  src/main/java/com/wellcom/domain/Reservation/Service/ReservationScheduler.java
  src/main/java/com/wellcom/domain/Reservation/Service/ReservationService.java
Labels: 리뷰 진행 중

#19 SharingRoom delYn 추가 및 delete 로직 수정
  src/main/java/com/wellcom/domain/SharingRoom/Dto/testDto.java
  src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
  src/main/java/com/wellcom/domain/SharingRoom/SharingRoom.java
Labels: 리뷰 진행 중

#21 [ADD] Image Upload and getUrl To S3
  build.gradle
  src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
  src/main/java/com/wellcom/domain/SharingRoom/config/S3Config.java
Labels: 리뷰 진행 중

#25 [UPDATE] update, delete 코드 수정 및 예외 처리로직 추가
  src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
  src/main/java/com/wellcom/global/error/ExceptionHandlerClass.java
Labels: 리뷰 진행 중

#26 [ADD] member CRUD 구현
  src/main/java/com/wellcom/WellComApplication.java
  src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
  src/main/java/com/wellcom/domain/Desk/Desk.java
  src/main/java/com/wellcom/domain/Desk/Service/DeskService.java
  src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
  src/main/java/com/wellcom/domain/Member/Dto/MemberDetailResDto.java
  src/main/java/com/wellcom/domain/Member/Dto/MemberListResDto.java
  src/main/java/com/wellcom/domain/Member/Dto/MemberListTotalResDto.java
  src/main/java/com/wellcom/domain/Member/Dto/MemberUpdateReqDto.java
  src/main/java/com/wellcom/domain/Member/Member.java
  src/main/java/com/wellcom/domain/Member/Repository/MemberRepository.java
  src/main/java/com/wellcom/domain/Member/Service/MemberService.java
  src/main/java/com/wellcom/domain/Reservation/Repository/ReservationRepository.java
  src/main/java/com/wellcom/domain/SharingRoom/Repository/SharingRoomRepository.java
  src/main/resources/application.yml
Labels: 수정 요청

#28 [ADD] Member CRUD 추가구현
  src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
  src/main/java/com/wellcom/domain/Member/Dto/MemberDetailResDto.java
  src/main/java/com/wellcom/domain/Member/Dto/ReservationDetailDto.java
  src/main/java/com/wellcom/domain/Member/Repository/MemberRepository.java
  src/main/java/com/wellcom/domain/Member/Service/MemberService.java
  src/main/java/com/wellcom/domain/Record/Repository/RecordRepository.java
  src/main/java/com/wellcom/domain/Reservation/Repository/ReservationRepository.java
Labels: 수정 요청

#30 [HOTFIX] 멤버 엔티티 수정 및 비밀번호 문자 표시 오류 해결
  front-end/src/components/SignInComponent.vue
  front-end/src/components/SignUpComponent.vue
  src/main/java/com/wellcom/domain/Member/Member.java
Labels: 리뷰 진행 중

#32 [ADD] Vue Main Header Component
  front-end/src/App.vue
  front-end/src/assets/background.jpg
  front-end/src/assets/logo.png
  front-end/src/assets/logo.svg
  front-end/src/assets/table.png
  front-end/src/components/HelloWorld.vue
  front-end/src/components/MainHeader.vue
  front-end/src/router/index.js
Labels: 완료

#33 [ADD] Main Footer
  front-end/src/App.vue
  front-end/src/components/MainFooter.vue
Labels: 완료

#34 [ADD] Table Reservation Page
  front-end/src/router/index.js
  front-end/src/views/TableHome.vue
Labels: 완료

#36 [FIX] 메인페이지 버튼 트랜지션 수정
  front-end/src/views/MainLanding.vue
Labels: 완료

#37 [FIX] 메인페이지 사이즈 크기별 반응형 추가
  front-end/src/views/MainLanding.vue
Labels: 완료

#40 [ADD] 테이블 예약 달력 추가
  front-end/src/App.vue
  front-end/src/assets/table.jpg
  front-end/src/assets/table.png
  front-end/src/views/TableHome.vue
Labels: 완료

#49 [FIX] 테이블 페이지 즉시사용버튼, 필터링 버튼 추가/ 예약 페이지 수정
  front-end/src/plugins/tokenPlugin.js
  front-end/src/views/TableHome.vue
Labels: 완료

#51 [ADD] admin page memberservice 구현
  front-end/src/components/AdminHomeForm.vue
  src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
Labels: 리뷰 진행 중

#54 [ADD] admin페이지 frontend 구현
  .DS_Store
  front-end/src/components/AdminHomeForm.vue
  front-end/src/router/AdminHomeRouter.js
  front-end/src/router/index.js
  front-end/src/router/mypageRouter.js
  front-end/src/views/AdminHomeForm.vue
  front-end/src/views/mypage.vue
  src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
Labels: 리뷰 진행 중

#55 [FIX] 날짜계산로직수정
  front-end/src/views/TableHome.vue
  src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
Labels: 완료

#61 [ADD] 테이블 3d 효과 추가
  front-end/src/views/TableHome.vue
  src/main/java/com/wellcom/domain/Desk/Desk.java
  src/main/java/com/wellcom/domain/Desk/Dto/DeskResDto.java
Labels: 완료

#62 [ADD] mypage frontend 구현
  front-end/src/App.vue
  front-end/src/views/mypage.vue
  src/main/java/com/wellcom/domain/SharingRoom/Service/SharingRoomService.java
Labels: 완료
